#!/bin/bash

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

declare -A G_TO_V

G_TO_V['com_github_beorn7_perks']='github.com/beorn7/perks'
G_TO_V['com_github_davecgh_go_spew']='github.com/davecgh/go-spew'
G_TO_V['com_github_emicklei_go_restful']='github.com/emicklei/go-restful'
G_TO_V['com_github_emicklei_go_restful_swagger12']='github.com/emicklei/go-restful-swagger12'
G_TO_V['com_github_ghodss_yaml']='github.com/ghodss/yaml'
G_TO_V['com_github_gogo_protobuf']='github.com/gogo/protobuf'
G_TO_V['com_github_golang_glog']='github.com/golang/glog'
G_TO_V['com_github_golang_protobuf']='github.com/golang/protobuf'
G_TO_V['com_github_googleapis_gax_go']='github.com/googleapis/gax-go'
G_TO_V['com_github_googleapis_gnostic']='github.com/googleapis/gnostic'
G_TO_V['com_github_google_gofuzz']='github.com/google/gofuzz'
G_TO_V['com_github_google_go_github']='github.com/google/go-github'
G_TO_V['com_github_google_go_querystring']='github.com/google/go-querystring'
G_TO_V['com_github_go_openapi_jsonpointer']='github.com/go-openapi/jsonpointer'
G_TO_V['com_github_go_openapi_jsonreference']='github.com/go-openapi/jsonreference'
G_TO_V['com_github_go_openapi_spec']='github.com/go-openapi/spec'
G_TO_V['com_github_go_openapi_swag']='github.com/go-openapi/swag'
G_TO_V['com_github_hashicorp_errwrap']='github.com/hashicorp/errwrap'
G_TO_V['com_github_hashicorp_golang_lru']='github.com/hashicorp/golang-lru'
G_TO_V['com_github_hashicorp_go_multierror']='github.com/hashicorp/go-multierror'
G_TO_V['com_github_howeyc_gopass']='github.com/howeyc/gopass'
G_TO_V['com_github_imdario_mergo']='github.com/imdario/mergo'
G_TO_V['com_github_juju_ratelimit']='github.com/juju/ratelimit'
G_TO_V['com_github_mailru_easyjson']='github.com/mailru/easyjson'
G_TO_V['com_github_matttproud_golang_protobuf_extensions']='github.com/matttproud/golang_protobuf_extensions'
G_TO_V['com_github_pkg_errors']='github.com/pkg/errors'
G_TO_V['com_github_pkg_errors']='github.com/pkg/errors'
G_TO_V['com_github_prometheus_client_golang']='github.com/prometheus/client_golang'
G_TO_V['com_github_prometheus_client_model']='github.com/prometheus/client_model'
G_TO_V['com_github_prometheus_common']='github.com/prometheus/common'
G_TO_V['com_github_prometheus_procfs']='github.com/prometheus/procfs'
G_TO_V['com_github_PuerkitoBio_purell']='github.com/PuerkitoBio/purell'
G_TO_V['com_github_PuerkitoBio_urlesc']='github.com/PuerkitoBio/urlesc'
G_TO_V['com_github_spf13_pflag']='github.com/spf13/pflag'
G_TO_V['com_github_ugorji_go']='github.com/ugorji/go'
G_TO_V['com_google_cloud_go']='cloud.google.com/go'
G_TO_V['in_gopkg_inf_v0']='gopkg.in/inf.v0'
G_TO_V['in_gopkg_yaml_v2']='gopkg.in/yaml.v2'
G_TO_V['io_k8s_api']='k8s.io/api'
G_TO_V['io_k8s_apimachinery']='k8s.io/apimachinery'
G_TO_V['io_k8s_client_go']='k8s.io/client-go'
G_TO_V['io_k8s_kube_openapi']='k8s.io/kube-openapi'
G_TO_V['org_golang_google_api']='google.golang.org/api'
G_TO_V['org_golang_google_appengine']='google.golang.org/appengine'
G_TO_V['org_golang_google_genproto']='google.golang.org/genproto'
G_TO_V['org_golang_google_grpc']='google.golang.org/grpc'
G_TO_V['org_golang_x_crypto']='golang.org/x/crypto'
G_TO_V['org_golang_x_net']='golang.org/x/net'
G_TO_V['org_golang_x_oauth2']='golang.org/x/oauth2'
G_TO_V['org_golang_x_sys']='golang.org/x/sys'
G_TO_V['org_golang_x_text']='golang.org/x/text'
G_TO_V['org_golang_x_tools']='golang.org/x/tools'

find ${ROOT} -type f -name BUILD -exec rm {} \;

bazel run //:gazelle
bazel run //:gazelle vendor/.

for key in ${!G_TO_V[@]}; do
  value="${G_TO_V["${key}"]}"
  find ${ROOT} -type f -name BUILD.bazel -exec sed -i  "s,@${key}//,//vendor/${value}/,g" {} \;
done

find ${ROOT} -type f -name BUILD.bazel -exec sed -i  "s,\(//vendor/.*\)/:,\1:,g" {} \;

${ROOT}/scripts/fmt.sh
